/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_z_s_S */

#ifndef _Included_com_z_s_S
#define _Included_com_z_s_S
#ifdef __cplusplus
extern "C" {
#endif
///*
// * Class:     com_z_s_S
// * Method:    setVtimeout
// * Signature: (I)I
// */
//JNIEXPORT jint JNICALL Java_com_z_s_S_setVtimeout
//  (JNIEnv *, jclass, jint);
//
///*
// * Class:     com_z_s_S
// * Method:    setStimeout
// * Signature: (II)I
// */
//JNIEXPORT jint JNICALL Java_com_z_s_S_setStimeout
//  (JNIEnv *, jclass, jint, jint);
//
///*
// * Class:     com_z_s_S
// * Method:    start
// * Signature: (Ljava/lang/String;ILjava/lang/String;)I
// */
//JNIEXPORT jint JNICALL Java_com_z_s_S_start
//  (JNIEnv *, jclass, jstring, jint, jstring);
//
///*
// * Class:     com_z_s_S
// * Method:    close
// * Signature: ()I
// */
//JNIEXPORT jint JNICALL Java_com_z_s_S_close
//  (JNIEnv *, jclass);
//
///*
// * Class:     com_z_s_S
// * Method:    getVcode
// * Signature: ()I
// */
//JNIEXPORT jint JNICALL Java_com_z_s_S_getVcode
//  (JNIEnv *, jclass);
//
///*
// * Class:     com_z_s_S
// * Method:    getVname
// * Signature: ()Ljava/lang/String;
// */
//JNIEXPORT jstring JNICALL Java_com_z_s_S_getVname
//  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
